name: main

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Run linter and pytest
        run: |
          make lint
      - name: Run Tests and generate coverage report
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pip install django
          pip install dj_database_url
          pip install load_dotenv
          pip install django_bootstrap5
          pip install psycopg2-binary
          pip install django-filter
          pip install rollbar
          pip install whitenoise
          pip install pytest-django
          pip install coverage

          coverage run --source='.' manage.py test
          coverage xml -o coverage.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectBaseDir: .
          args: "-Dsonar.coverageReportPaths=coverage.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
