name: main

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests and generate coverage report
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pip install django
          pip install dj_database_url
          pip install load_dotenv
          pip install django_bootstrap5
          pip install psycopg2-binary
          pip install django-filter
          pip install rollbar
          pip install whitenoise
          pip install pytest-django
          pip install coverage

          coverage run --source='.' manage.py test
          coverage xml -o coverage.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install SonarScanner
        run: npm install -g sonar-scanner

      - name: Run SonarScanner manually
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=pikachy337 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.python.coverage.reportPaths=coverage.xml
